appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c3107604e246e0700ce91fe
  secret: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: cBBulDUSF4IvI59O9g1YmrYzAdOgnMFQh4rpEnz6guOioj+pqjw2tisuW9oVnbxNTDqYJJkCK3fyCsS6oONAVS2W4qvWCeLJp8kRjfvEr6S5hLOmMi8nJs+6fXf5UvlBtWGofJ7NExQIxbh4Zgd+cfrirMrYLqt5DHlc041UxPBd8E9LO3CwfN8fXJbgKh1xy0mJz+Ru6d79neP/3s1taVreRCcv+F30ZYCWclIfgo+Bn1JfRnLLY4qMVFZVE10hvJWEvT4M1Bj1icu2bBXyL6ay6qhmlLuIS6fFJk7jpLj/qWi+rl9q/XKJt4ILmyV4apeKrJFQ7N7uwLg/NxgjeEHOkjx9+5yanbGCKLuJj+J8+HweFl2thdrda9v0STH3AsISBdu1llaxcMjnYbJqHVt/xrbv3cJyFo6ucljmEsHH4PNH4r6OJt4sCV1njkAB6YXnIel5Bmk+qUSsLtM4c3vN+6x/lBSGSEmK8vualnRVHiOKef5JYKLfKsJPNutLtdBt18DFJa5ebl36snhROAbZHpN3ydD6HRADYL7AXOiOZ9aeVylMXviNVprkl/g/Ii0RQuaOd0yNG7LFMZpNvKu8my4MdRr053glqMkgLH8WrRjY+H7rcUltGd/hR1AECYkPGvF6sMk2JSjwwc7pLbXSepphlHy92Q4BOf3lpWQ=}
